name: rento
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  equatable: ^2.0.3

  # state management
  flutter_riverpod: ^1.0.4
  flutter_bloc: ^8.0.1

  # local storage
  dependencies:
  drift: ^1.7.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.1

  # cloud
  cloud_firestore: ^3.4.2
  firebase_core: ^1.20.0

  #styling
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_web_compilers: ^3.2.1

  drift_dev: ^1.7.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
